name: Build and Deploy Azure Function (Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo root
        run: |
          pwd
          ls -la

      - name: Deploy to Azure Functions (Oryx build)
        uses: azure/functions-action@v1
        with:
          app-name: bubble-snowflake-api          # <-- put your real Function App name
          package: .                                # repo root (contains host.json, requirements.txt)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          scm-do-build-during-deployment: true      # server-side build so requirements.txt installs
